
name: Shell commands to run
on: push
jobs:
  functions: 
    runs-on: ubuntu-latest
    steps: 
      - name: dump
        run: |
         echo ${{ contains('hello', 'll') }}
         echo ${{ startswith('hello', 'hel') }}
         echo ${{ endswith('hello', 'lo') }}
