
name: Shell commands

on: [push]

jobs:
  function: 
    runs-on: ubuntu-latest
    steps: 
      - name: dummp
        run: |
         echo @{{ contains('hello', 'll') }}
         echo @{{ startwith('hello', 'hel') }}
         echo @{{ endswith('hello', 'lo') }}
