name: change version
on: 
  push:
   paths:
     - /.github/workflows/first.yml

jobs:
  node-version:
    runs-on: ubuntu-latest

    steps:
      - name: current version123
        run: node -v
      - name: Checkout private tool
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: 12
          token: ${{ secrets.GH_PAT }}

      - name: current version
        run: node -v