name: change version
on: push

jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: current version123
        run: node -v
      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: 12
          token: ${{ secrets.GH_PAT }}

      - name: current version
        run: node -v