name: change version
on: push

jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: current version123
        run: node -v
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          token: ${{ secrets.GH_PAT }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
         #token: ${{ secrets.GH_PAT || github.token }}
          token: ${{ secrets.GH_PAT }}
         #token: ${{ secrets.GITHUB_TOKEN }}
      - name: current version
        run: node -v